name: autoverify
description: "A Flutter project for automatic payment verification via SMS and Notifications."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Core Logic
  sqflite: ^2.3.2
  path: ^1.9.0
  dio: ^5.4.1
  crypto: ^3.0.3
  intl: ^0.19.0
  logger: ^2.0.0
  uuid: ^4.3.3
  
  # State Management
  provider: ^6.1.1
  
  # Background & Permissions
  workmanager: ^0.5.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  
  # Platform Channels / Hardware
  telephony: ^0.2.0
  flutter_notification_listener: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
